const DIMENSIONS=[{id:1,name:"Realista"},{id:2,name:"Investigador"},{id:3,name:"Social"},{id:4,name:"Convencional"},{id:5,name:"Emprendedor"},{id:6,name:"Artístico"}];
const A_ITEMS=[[1,"Huraño"],[2,"Discutidor"],[3,"Arrogante"],[4,"Capaz"],[5,"Común y corriente"],[6,"Conformista"],[7,"Concienzudo"],[8,"Curioso"],[9,"Dependiente"],[10,"Eficiente"],[11,"Paciente"],[12,"Dinámico"],[13,"Femenino"],[14,"Amistoso"],[15,"Generoso"],[16,"Dispuesto a ayudar"],[17,"Inflexible"],[18,"Insensible"],[19,"Introvertido"],[20,"Intuitivo"],[21,"Irritable"],[22,"Amable"],[23,"De buenos modales"],[24,"Varonil"],[25,"Inconforme"],[26,"Poco realista"],[27,"Poco culto"],[28,"Poco idealista"],[29,"Impopular"],[30,"Original"],[31,"Pesimista"],[32,"Hedonista"],[33,"Práctico"],[34,"Rebelde"],[35,"Reservado"],[36,"Culto"],[37,"Lento de movimientos"],[38,"Sociable"],[39,"Estable"],[40,"Esforzado"],[41,"Fuerte"],[42,"Suspicaz"],[43,"Cumplido"],[44,"Modesto"],[45,"Poco convencional"]];
const A_MAP={1:[3,11,18,21,24,27,35,44],2:[8,19,29,31,33,36,37,43],3:[4,14,15,16,17,22,28,42],4:[5,6,7,9,10,26,40,41],5:[2,12,23,32,38,39,45],6:[1,13,20,25,30,34]};
const B_ITEMS=[[1,"Distraído"],[2,"Capacidad artística"],[3,"Capacidad burocrática"],[4,"Conservador"],[5,"Cooperación"],[6,"Expresividad"],[7,"Liderazgo"],[8,"Gusto en ayudar a los demás"],[9,"Capacidad matemática"],[10,"Capacidad mecánica"],[11,"Originalidad"],[12,"Popularidad con el sexo opuesto"],[13,"Capacidad para investigar"],[14,"Capacidad científica"],[15,"Seguridad en sí mismo"],[16,"Comprensión de sí mismo"],[17,"Comprensión de los demás"],[18,"Pulcritud"]];
const B_MAP={1:[1,10,16],2:[9,13,14],3:[5,8,17],4:[3,4,18],5:[7,12,15],6:[2,6,11]};
const C_ITEMS=[[1,"Estar feliz y satisfecho"],[2,"Descubrir o elaborar un producto útil"],[3,"Ayudar a quienes están en apuros"],[4,"Llegar a ser una autoridad en algún tema"],[5,"Llegar a ser un deportista destacado"],[6,"Llegar a ser un líder en la comunidad"],[7,"Ser influyente en asuntos públicos"],[8,"Observar una conducta religiosa formal"],[9,"Contribuir a la ciencia en forma teórica"],[10,"Contribuir a la ciencia en forma técnica"],[11,"Escribir bien (novelas, poemas)"],[12,"Haber leído mucho"],[13,"Trabajar mucho"],[14,"Contribuir al bienestar humano"],[15,"Crear buenas obras artísticas (teatro, pintura)"],[16,"Llegar a ser un buen músico"],[17,"Llegar a ser un experto en finanzas y negocios"],[18,"Hallar un propósito real en la vida"]];
const C_MAP={1:[2,5,12],2:[4,9,10],3:[3,14,18],4:[1,8,13],5:[6,7,17],6:[11,15,16]};
const D_ITEMS=[{q:1,title:"Me gusta…",options:{a:"Leer y meditar sobre los problemas",b:"Anotar datos y hacer cómputos",c:"Tener una posición poderosa",d:"Enseñar o ayudar a los demás",e:"Trabajar manualmente, usar equipos, herramientas",f:"Usar mi talento artístico"}},{q:2,title:"Mi mayor habilidad se manifiesta en…",options:{a:"Negocios",b:"Artes",c:"Ciencias",d:"Liderazgo",e:"Relaciones humanas",f:"Mecánica"}},{q:3,title:"Soy muy incompetente en…",options:{a:"Mecánica",b:"Ciencia",c:"Relaciones humanas",d:"Negocios",e:"Liderazgo",f:"Artes"}},{q:4,title:"Si tuviera que realizar alguna de estas actividades, la que menos me agradaría es…",options:{a:"Participar en actividades sociales muy formales",b:"Tener una posición de responsabilidad",c:"Llevar pacientes mentales a actividades recreativas",d:"Llevar registros exactos y complejos",e:"Escribir un poema",f:"Hacer algo que exija paciencia y precisión"}},{q:5,title:"Las materias que más me gustan son…",options:{a:"Arte",b:"Administración, contabilidad",c:"Química, Física",d:"Educación tecnológica, Mecánica",e:"Historia",f:"Ciencias sociales, Filosofía"}}];
const D_MAP={1:{e:1,a:2,d:3,b:4,c:5,f:6},2:{f:1,c:2,e:3,a:4,d:5,b:6},3:{c:1,e:2,a:3,f:4,b:5,d:6},4:{b:1,f:2,e:3,d:4,a:5,c:6},5:{d:1,c:2,f:3,b:4,e:5,a:6}};
const INTERPRETATIONS={1:{title:"Realista",text:"Prefiere actividades prácticas, concretas y ligadas al uso de herramientas, equipos, máquinas o procedimientos visibles. Tiende a valorar lo tangible y la solución directa de problemas."},2:{title:"Investigador",text:"Se inclina por observar, analizar, investigar y comprender fenómenos con lógica, datos y pensamiento crítico. Suele mostrar interés por la ciencia y la exploración intelectual."},3:{title:"Social",text:"Se orienta al trabajo con personas: ayudar, enseñar, acompañar, guiar y colaborar. Valora lo humano, la comunicación y el servicio."},4:{title:"Convencional",text:"Prefiere el orden, la organización, los datos, los procedimientos y los sistemas claros. Suele sentirse cómodo con estructuras definidas y tareas metódicas."},5:{title:"Emprendedor",text:"Tiende a liderar, persuadir, tomar decisiones y movilizar a otros para alcanzar objetivos. Valora el logro, la iniciativa y el impacto."},6:{title:"Artístico",text:"Busca crear, expresarse y trabajar con libertad, imaginación y originalidad. Suele inclinarse por el arte, el lenguaje, la música o formas no rutinarias de resolver problemas."}};
const partAEl=document.getElementById("partA"),partBEl=document.getElementById("partB"),partCEl=document.getElementById("partC"),partDEl=document.getElementById("partD"),resultCardsEl=document.getElementById("resultCards"),summaryBodyEl=document.getElementById("summaryBody"),top3PillsEl=document.getElementById("top3Pills"),interpretationsEl=document.getElementById("interpretations"),progressTextEl=document.getElementById("progressText"),progressBarEl=document.getElementById("progressBar"),calculateBtn=document.getElementById("calculateBtn"),resetBtn=document.getElementById("resetBtn"),navToggle=document.getElementById("navToggle"),navMenu=document.getElementById("navMenu");
function renderPartA(){partAEl.innerHTML=A_ITEMS.map(([n,text])=>`<label class="check-item"><input type="checkbox" name="A_${n}"><span><strong>${n}.</strong> ${text}</span></label>`).join("");}
function rowRadio(group,value){return `<label><input type="radio" name="${group}" value="${value}"></label>`;}
function renderPartB(){partBEl.innerHTML=B_ITEMS.map(([n,text])=>`<tr><td>${n}</td><td>${text}</td><td>${rowRadio(`B_${n}`,"A")}</td><td>${rowRadio(`B_${n}`,"B")}</td><td>${rowRadio(`B_${n}`,"C")}</td></tr>`).join("");}
function renderPartC(){partCEl.innerHTML=C_ITEMS.map(([n,text])=>`<tr><td>${n}</td><td>${text}</td><td>${rowRadio(`C_${n}`,"A")}</td><td>${rowRadio(`C_${n}`,"B")}</td><td>${rowRadio(`C_${n}`,"C")}</td></tr>`).join("");}
function renderPartD(){partDEl.innerHTML=D_ITEMS.map(item=>`<div class="question-card"><h3>${item.q}. ${item.title}</h3><div class="options">${Object.entries(item.options).map(([k,v])=>`<label class="option"><input type="radio" name="D_${item.q}" value="${k}"><span><strong>${k.toUpperCase()})</strong> ${v}</span></label>`).join("")}</div></div>`).join("");}
function initScores(){const obj={A:{},B:{},C:{},D:{},TOTAL:{}};DIMENSIONS.forEach(dim=>{obj.A[dim.id]=0;obj.B[dim.id]=0;obj.C[dim.id]=0;obj.D[dim.id]=0;obj.TOTAL[dim.id]=0;});return obj;}
function getSelectedA(){return A_ITEMS.map(([n])=>n).filter(n=>document.querySelector(`input[name="A_${n}"]`)?.checked);}
function scoreByMapSelected(selectedNumbers,map){const scores={};Object.keys(map).forEach(dim=>{scores[dim]=map[dim].filter(num=>selectedNumbers.includes(num)).length;});return scores;}
function scoreABorC(prefix,items,map){const scores={},missing=[];Object.keys(map).forEach(dim=>scores[dim]=0);items.forEach(([n])=>{const value=document.querySelector(`input[name="${prefix}_${n}"]:checked`)?.value;if(!value)missing.push(`${prefix}${n}`);if(value==="A"){Object.entries(map).forEach(([dim,arr])=>{if(arr.includes(n))scores[dim]+=1;});}});return{scores,missing};}
function scorePartD(){const scores={},missing=[];DIMENSIONS.forEach(dim=>scores[dim.id]=0);D_ITEMS.forEach(item=>{const value=document.querySelector(`input[name="D_${item.q}"]:checked`)?.value;if(!value)missing.push(`D${item.q}`);else{const dim=D_MAP[item.q][value];if(dim)scores[dim]+=1;}});return{scores,missing};}
function computeResults(){const breakdown=initScores();const selectedA=getSelectedA(),aScores=scoreByMapSelected(selectedA,A_MAP);Object.keys(aScores).forEach(dim=>breakdown.A[dim]=aScores[dim]);const partB=scoreABorC("B",B_ITEMS,B_MAP);Object.keys(partB.scores).forEach(dim=>breakdown.B[dim]=partB.scores[dim]);const partC=scoreABorC("C",C_ITEMS,C_MAP);Object.keys(partC.scores).forEach(dim=>breakdown.C[dim]=partC.scores[dim]);const partD=scorePartD();Object.keys(partD.scores).forEach(dim=>breakdown.D[dim]=partD.scores[dim]);DIMENSIONS.forEach(dim=>{breakdown.TOTAL[dim.id]=breakdown.A[dim.id]+breakdown.B[dim.id]+breakdown.C[dim.id]+breakdown.D[dim.id];});return{breakdown,missing:[...partB.missing,...partC.missing,...partD.missing]};}
function renderResults(data){const totals=data.breakdown.TOTAL,max=Math.max(...Object.values(totals),1);resultCardsEl.innerHTML=DIMENSIONS.map(dim=>{const val=totals[dim.id],pct=Math.round((val/max)*100);return `<div class="result-card"><h3>${dim.name}</h3><div class="result-value">${val}</div><div class="bar"><span style="width:${pct}%"></span></div></div>`;}).join("");summaryBodyEl.innerHTML=DIMENSIONS.map(dim=>`<tr><td><strong>${dim.name}</strong></td><td>${data.breakdown.A[dim.id]}</td><td>${data.breakdown.B[dim.id]}</td><td>${data.breakdown.C[dim.id]}</td><td>${data.breakdown.D[dim.id]}</td><td><strong>${data.breakdown.TOTAL[dim.id]}</strong></td></tr>`).join("");const sorted=Object.entries(totals).map(([id,total])=>({id:Number(id),total})).sort((a,b)=>b.total-a.total);const top3=sorted.slice(0,3);top3PillsEl.innerHTML=top3.map((item,index)=>`<span class="pill">${index+1}. ${DIMENSIONS.find(d=>d.id===item.id).name} · ${item.total}</span>`).join("");const topSet=new Set(top3.map(item=>item.id));interpretationsEl.innerHTML=DIMENSIONS.map(dim=>`<div class="interp-card" style="${topSet.has(dim.id)?'box-shadow:0 0 0 2px rgba(143,116,247,.18) inset;':''}"><h3>${INTERPRETATIONS[dim.id].title}${topSet.has(dim.id)?' · En tu top 3':''}</h3><p>${INTERPRETATIONS[dim.id].text}</p></div>`).join("");const top1=sorted[0];if(top1){const dim=DIMENSIONS.find(d=>d.id===top1.id),interp=INTERPRETATIONS[top1.id];const top1El=document.getElementById("resultTop1Card");if(top1El){top1El.innerHTML=`<div class="result-top1-card__label">Tu resultado principal</div><div class="result-top1-card__title">${interp?interp.title:dim.name}</div><p class="result-top1-card__desc">${interp?interp.text:""}</p>`;top1El.style.display="block";}}}
function updateProgress(){const totalRequired=B_ITEMS.length+C_ITEMS.length+D_ITEMS.length;let completed=0;B_ITEMS.forEach(([n])=>{if(document.querySelector(`input[name="B_${n}"]:checked`))completed++;});C_ITEMS.forEach(([n])=>{if(document.querySelector(`input[name="C_${n}"]:checked`))completed++;});D_ITEMS.forEach(item=>{if(document.querySelector(`input[name="D_${item.q}"]:checked`))completed++;});const pct=Math.round((completed/totalRequired)*100);progressTextEl.textContent=`${pct}%`;progressBarEl.style.width=`${pct}%`;}
function gatherAnswers(){const answers={A:[],B:{},C:{},D:{}};A_ITEMS.forEach(([n])=>{if(document.querySelector(`input[name="A_${n}"]`)?.checked)answers.A.push(n);});B_ITEMS.forEach(([n])=>{answers.B[n]=document.querySelector(`input[name="B_${n}"]:checked`)?.value||null;});C_ITEMS.forEach(([n])=>{answers.C[n]=document.querySelector(`input[name="C_${n}"]:checked`)?.value||null;});D_ITEMS.forEach(item=>{answers.D[item.q]=document.querySelector(`input[name="D_${item.q}"]:checked`)?.value||null;});return answers;}
function resetAll(){document.querySelectorAll('input[type="checkbox"]').forEach(el=>el.checked=false);document.querySelectorAll('input[type="radio"]').forEach(el=>el.checked=false);if(resultCardsEl)resultCardsEl.innerHTML="";if(summaryBodyEl)summaryBodyEl.innerHTML="";if(interpretationsEl)interpretationsEl.innerHTML="";if(top3PillsEl)top3PillsEl.innerHTML='<span class="pill">Completa el test para ver tu perfil.</span>';updateProgress();location.hash="#test";}
function downloadResults(){const computed=computeResults();const payload={test:"Holland",generatedAt:new Date().toISOString(),answers:gatherAnswers(),results:computed.breakdown};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`resultado_holland_${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}
function showResultsView(){const qs=document.getElementById("questionsSection"),rs=document.getElementById("resultadosSection");if(qs){qs.classList.add("is-hidden");}if(rs){rs.classList.remove("is-hidden");rs.setAttribute("aria-hidden","false");rs.scrollIntoView({behavior:"smooth",block:"start"});}}
function showQuestionsView(){const qs=document.getElementById("questionsSection"),rs=document.getElementById("resultadosSection");if(qs){qs.classList.remove("is-hidden");}if(rs){rs.classList.add("is-hidden");rs.setAttribute("aria-hidden","true");}const top1El=document.getElementById("resultTop1Card");if(top1El){top1El.style.display="none";top1El.innerHTML="";}}
calculateBtn.addEventListener("click",()=>{const computed=computeResults();if(computed.missing.length){alert(`Faltan respuestas obligatorias en: ${computed.missing.join(", ")}\.\n\nCompleta la Parte B, C y D para calcular correctamente el perfil.`);return;}renderResults(computed);showResultsView();});
resetBtn.addEventListener("click",()=>{resetAll();showQuestionsView();});
document.getElementById("backToQuestionsBtn")?.addEventListener("click",()=>{showQuestionsView();document.getElementById("test")?.scrollIntoView({behavior:"smooth"});});
document.addEventListener("change",e=>{if(e.target.matches('input[type="checkbox"], input[type="radio"]'))updateProgress();});navToggle?.addEventListener("click",()=>{const isOpen=navMenu.classList.toggle("is-open");navToggle.setAttribute("aria-expanded",String(isOpen));});renderPartA();renderPartB();renderPartC();renderPartD();updateProgress();